version: "3.9"
services:
  baget:
    image: "loicsharma/baget:latest"
    env_file:
      - "./Baget/baget.env"
    ports:
      - "5555:5555"
      - "5556:80"
    volumes:
      - "./Baget/baget-data:/var/baget"
  eventstore.db:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - "./esdb/data:/var/lib/eventstore"
      - "./esdb/logs:/var/log/eventstore"
