version: "3.9"

services:
  baget:
    image: "loicsharma/baget:latest"
    env_file:
      - "./Baget/baget.env"
    ports:
      - "5555:5555"
      - "5556:80"
    volumes:
      - "./Baget/baget-data:/var/baget"
    networks:
      - build

networks:
  build:
    driver: bridge
